---
driver:
  name: vagrant
  vm_hostname: Task3

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.8

suites:
  - name: default
    run_list:
      - recipe[Task3::default]
      - recipe[Task3::apache]
      - recipe[Task3::firewall]
    attributes:
