name             'Task3'
maintainer       'Dmytro'
maintainer_email 'dfad1ripe@gmail.com'
license          'none'
description      'MySQL backups'
long_description 'Installs/Configures MySQL with scheduled backups'
version          '0.1.0'
issues_url       'http://bash.im/'
source_url       'https://github.com/dfad1ripe/df_devops_task3'
depends          'selinux', '~> 0.9.0'
depends          'mysql', '~> 8.0'
depends          'apache2', '~> 3.2.2'
