name             'Task3'
maintainer       'Dmytro'
maintainer_email 'dfad1ripe@gmail.com'
license          'none'
description      'MySQL backups'
long_description 'Installs/Configures MySQL with scheduled backups'
version          '0.1.2'
issues_url       'http://bash.im/'
source_url       'https://github.com/dfad1ripe/df_devops_task3'
depends          'build-essential'
depends          'selinux'
depends          'yum_mysql_community'
depends          'mysql'
depends          'mysql2_chef_gem'
depends          'database'
depends          'cron'
depends          'apache2'
depends          'iptables'
